import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faFunnelDollar,
  faHandHoldingUsd,
  faGift,
  faCommentDollar,
  faGavel,
  faDownload,
  faComments,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faTrophy,
  faVoteYea,
  faReceipt,
  faBalanceScaleRight,
  faSuitcase,
  faBriefcase,
  faFileSignature,
  faInfoCircle,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faFunnelDollar,
  faHandHoldingUsd,
  faGift,
  faCommentDollar,
  faGavel,
  faDownload,
  faComments,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faTrophy,
  faVoteYea,
  faReceipt,
  faBalanceScaleRight,
  faSuitcase,
  faBriefcase,
  faFileSignature,
  faInfoCircle
);
